require "plugins"
-- require "impatient"
require "options"
require "keymaps"
require "comment"
require "autopairs"
require "zen"
require "neotree"
require "tabline"
require "statusline"
require "hop-config"
require "cmp-config"
require "lsp"
require "telescope-config"
require "gitsigns-config"
